### ISSUE TITLE
几个问题

### ISSUE THREAD

**Issue by zhzipu** [GlaringMarvel/Aokana-Flying-Circus#5]
1.减速板异常打开(经常)：飞机经常在刚起飞时就打开减速板，情况大部分出现的地图是“西奈半岛”(**炸弹也会提前投放**)。
2.脚本在战局结束时会崩溃（经常）：不知道什么规律，挂的越久崩溃的概率越大，不报错程序直接自己关闭。
3.脚本识别战局结束速度慢：经常死了好久才去匹配下一局整个过程一分钟左右
4.开局向下拉机头（偶尔）：出现次数很少，找不到规律。
5.print优化：希望print能增加距离战区的距离，方便配置飞机设置

**Comment by GlaringMarvel** [comment]
> 1.减速板异常打开(经常)：飞机经常在刚起飞时就打开减速板，情况大部分出现的地图是“西奈半岛”(**炸弹也会提前投放**)。 2.脚本在战局结束时会崩溃（经常）：不知道什么规律，挂的越久崩溃的概率越大，不报错程序直接自己关闭。 3.脚本识别战局结束速度慢：经常死了好久才去匹配下一局整个过程一分钟左右 4.开局向下拉机头（偶尔）：出现次数很少，找不到规律。 5.print优化：希望print能增加距离战区的距离，方便配置飞机设置

以下情况是基于你使用的我最新发布的文件：
1.减速板问题我对判断做了修改，虽然我之前本地没有测出来问题，但是我找到了可能的原因，现在如果不想开启减速板需要把减速板的值改为-1
2.无报错关闭我会去关注，这个原因太多我需要慢慢排查，甚至有可能是python自身的原因
3.我在8111端口是找不到飞机死完判定的，只能等飞机掉到地上才能判断飞机是否死亡，虽然过程慢但是判断准确，如果有什么其他好的建议可以提出来
4.开局下压机头我并没有找到原因
5.在飞机开启ccrp之后，windows的黑色Dos窗口是会打印输出距离战区的剩余距离，我这个功能一开始就加了，数值在战区坐标飞机坐标后面
感谢测试与反馈

**Comment by GlaringMarvel** [comment]
> 1.减速板异常打开(经常)：飞机经常在刚起飞时就打开减速板，情况大部分出现的地图是“西奈半岛”(**炸弹也会提前投放**)。 2.脚本在战局结束时会崩溃（经常）：不知道什么规律，挂的越久崩溃的概率越大，不报错程序直接自己关闭。 3.脚本识别战局结束速度慢：经常死了好久才去匹配下一局整个过程一分钟左右 4.开局向下拉机头（偶尔）：出现次数很少，找不到规律。 5.print优化：希望print能增加距离战区的距离，方便配置飞机设置

补充一点，如果是开局起飞后炸弹自动扔出去，可能是游戏判定一直按着投弹键，每次关了脚本以后按两下U键刷新下输入，投弹是CCRP，也就是游戏控制的，如果CCRP开启以后，投弹行为就不是脚本能掌控的了。我已经重新上传了版本，还在老地方下载

**Comment by zhzipu** [comment]
是“阿富汗”大概率会死在跑道上

**Comment by zhzipu** [comment]
> > 1.减速板异常打开(经常)：飞机经常在刚起飞时就打开减速板，情况大部分出现的地图是“西奈半岛”(**炸弹也会提前投放**)。 2.脚本在战局结束时会崩溃（经常）：不知道什么规律，挂的越久崩溃的概率越大，不报错程序直接自己关闭。 3.脚本识别战局结束速度慢：经常死了好久才去匹配下一局整个过程一分钟左右 4.开局向下拉机头（偶尔）：出现次数很少，找不到规律。 5.print优化：希望print能增加距离战区的距离，方便配置飞机设置
> 
> 以下情况是基于你使用的我最新发布的文件： 1.减速板问题我对判断做了修改，虽然我之前本地没有测出来问题，但是我找到了可能的原因，现在如果不想开启减速板需要把减速板的值改为-1 2.无报错关闭我会去关注，这个原因太多我需要慢慢排查，甚至有可能是python自身的原因 3.我在8111端口是找不到飞机死完判定的，只能等飞机掉到地上才能判断飞机是否死亡，虽然过程慢但是判断准确，如果有什么其他好的建议可以提出来 4.开局下压机头我并没有找到原因 5.在飞机开启ccrp之后，windows的黑色Dos窗口是会打印输出距离战区的剩余距离，我这个功能一开始就加了，数值在战区坐标飞机坐标后面 感谢测试与反馈

减速板是设置了适当的距离开启，但是在“西奈半岛”飞机起飞之后在CCRP设置之前就会打开减速板把炸弹释放。

**Comment by GlaringMarvel** [comment]
> > > 1.减速板异常打开(经常)：飞机经常在刚起飞时就打开减速板，情况大部分出现的地图是“西奈半岛”(**炸弹也会提前投放**)。 2.脚本在战局结束时会崩溃（经常）：不知道什么规律，挂的越久崩溃的概率越大，不报错程序直接自己关闭。 3.脚本识别战局结束速度慢：经常死了好久才去匹配下一局整个过程一分钟左右 4.开局向下拉机头（偶尔）：出现次数很少，找不到规律。 5.print优化：希望print能增加距离战区的距离，方便配置飞机设置
> > 
> > 
> > 以下情况是基于你使用的我最新发布的文件： 1.减速板问题我对判断做了修改，虽然我之前本地没有测出来问题，但是我找到了可能的原因，现在如果不想开启减速板需要把减速板的值改为-1 2.无报错关闭我会去关注，这个原因太多我需要慢慢排查，甚至有可能是python自身的原因 3.我在8111端口是找不到飞机死完判定的，只能等飞机掉到地上才能判断飞机是否死亡，虽然过程慢但是判断准确，如果有什么其他好的建议可以提出来 4.开局下压机头我并没有找到原因 5.在飞机开启ccrp之后，windows的黑色Dos窗口是会打印输出距离战区的剩余距离，我这个功能一开始就加了，数值在战区坐标飞机坐标后面 感谢测试与反馈
> 
> 减速板是设置了适当的距离开启，但是在“西奈半岛”飞机起飞之后在CCRP设置之前就会打开减速板把炸弹释放。

阿富汗的问题是我之前偷懒没有改默认值，需要手动去Map.txt里调整飞行高度（因为我没有阿富汗的飞行高度数据）
西奈半岛的问题我没有头绪，如果在出现问题的时候你能记录下Dos窗口上的飞机坐标，战区坐标，战区距离，以及各种数据，那将有助于我找到问题

**Comment by zhzipu** [comment]
西奈半岛的录像
https://wwi.lanzoup.com/i34kP15t8mef

**Comment by zhzipu** [comment]
> > > > 1.减速板异常打开(经常)：飞机经常在刚起飞时就打开减速板，情况大部分出现的地图是“西奈半岛”(**炸弹也会提前投放**)。 2.脚本在战局结束时会崩溃（经常）：不知道什么规律，挂的越久崩溃的概率越大，不报错程序直接自己关闭。 3.脚本识别战局结束速度慢：经常死了好久才去匹配下一局整个过程一分钟左右 4.开局向下拉机头（偶尔）：出现次数很少，找不到规律。 5.print优化：希望print能增加距离战区的距离，方便配置飞机设置
> > > 
> > > 
> > > 以下情况是基于你使用的我最新发布的文件： 1.减速板问题我对判断做了修改，虽然我之前本地没有测出来问题，但是我找到了可能的原因，现在如果不想开启减速板需要把减速板的值改为-1 2.无报错关闭我会去关注，这个原因太多我需要慢慢排查，甚至有可能是python自身的原因 3.我在8111端口是找不到飞机死完判定的，只能等飞机掉到地上才能判断飞机是否死亡，虽然过程慢但是判断准确，如果有什么其他好的建议可以提出来 4.开局下压机头我并没有找到原因 5.在飞机开启ccrp之后，windows的黑色Dos窗口是会打印输出距离战区的剩余距离，我这个功能一开始就加了，数值在战区坐标飞机坐标后面 感谢测试与反馈
> > 
> > 
> > 减速板是设置了适当的距离开启，但是在“西奈半岛”飞机起飞之后在CCRP设置之前就会打开减速板把炸弹释放。
> 
> 阿富汗的问题是我之前偷懒没有改默认值，需要手动去Map.txt里调整飞行高度（因为我没有阿富汗的飞行高度数据） 西奈半岛的问题我没有头绪，如果在出现问题的时候你能记录下Dos窗口上的飞机坐标，战区坐标，战区距离，以及各种数据，那将有助于我找到问题

https://wwi.lanzoup.com/i34kP15t8mef
西奈半岛的录像
